# -*- coding: utf-8 -*-
"""반려견 결막염 진단 보조 인공지능 의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JitBIaJc2JecJvam_-r-P5ScYU0i28Hr

## 데이터셋 다운로드 및 압축해제

- 샘플데이터 600장
  - 정상(Negative): 300장
  - 결막염(Positive): 300장
"""

import os
!ls
!cd dog-inflammation
!ls -al

"""/content/sample_data"""

!wget https://github.com/kairess/toy-datasets/raw/master/dog-inflammation.zip
!unzip -q dog-inflammation.zip

"""## 데이터 로더"""

from fastai.vision.all import *

path = 'dog-inflammation'

block = DataBlock(
    blocks = (ImageBlock, CategoryBlock),
    get_items = get_image_files,
    get_y = parent_label,
)

loader = block.dataloaders(path)

loader.show_batch()

"""## 학습

Fine-tune ResNet18
"""

learn = vision_learner(loader, resnet18, metrics=accuracy)

learn.fine_tune(epochs = 3)

"""## 테스트 결과"""

learn.show_results()

"""## GradCAM

주요 인식 부위 시각화
"""

neg_path = '/content/dog-inflammation/Negative/D0_03f7e7c0-60a5-11ec-8402-0a7404972c70.jpg'
pos_path = '/content/dog-inflammation/Positive/D0_02fa7d26-60a5-11ec-8402-0a7404972c70.jpg'

test_loader = loader.test_dl([neg_path, pos_path])

neg_x, pos_x = next(iter(test_loader))[0]

neg_x = neg_x.unsqueeze(0)
pos_x = pos_x.unsqueeze(0)

print(neg_x.shape, pos_x.shape)

neg_img = Image.open(neg_path)
pos_img = Image.open(pos_path)

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(neg_img)
ax[0].axis('off')
ax[1].imshow(pos_img)
ax[1].axis('off')
plt.tight_layout()
plt.show()

class Hook():
    def __init__(self, m):
        self.hook = m.register_forward_hook(self.hook_func)
    def hook_func(self, m, i, o):
        self.stored = o.detach().clone()
    def __enter__(self, *args):
        return self
    def __exit__(self, *args):
        self.hook.remove()

class HookBwd():
    def __init__(self, m):
        self.hook = m.register_backward_hook(self.hook_func)
    def hook_func(self, m, gi, go):
        self.stored = go[0].detach().clone()
    def __enter__(self, *args):
        return self
    def __exit__(self, *args):
        self.hook.remove()

"""output = learn.model.eval()(x.cuda()) 에서
            output = learn.model.eval()(x) 수정

get_gradcam 함수:

get_gradcam 함수는 주어진 입력 x에 대해 Grad-CAM을 계산합니다.
HookBwd와 Hook을 사용하여 forward pass와 backward pass 중간에 특정 레이어의 활성화 값과 gradient를 추출합니다.
output = learn.model.eval()(x.cuda()): 모델을 사용하여 입력을 전달하고 출력을 계산합니다.
idx = torch.argmax(output): 출력의 최댓값 위치를 찾습니다.
act = hook.stored: 해당 레이어의 활성화 값을 가져옵니다.
output[0, idx].backward(): 최댓값 위치의 gradient를 계산합니다.
grad = hookg.stored: 해당 레이어의 gradient 값을 가져옵니다.
Grad-CAM을 계산하기 위해 gradient와 활성화 값을 조합하여 heatmap을 만듭니다.
마지막으로, heatmap을 시각화하기 위해 Matplotlib을 사용하여 이미지를 표시합니다.

이 코드는 모델의 특정 레이어에서 활성화와 gradient를 추출하여 Grad-CAM을 생성하는 기법을 사용합니다. 시각적인 heatmap으로 모델이 어떤 부분에 집중하고 있는지를 시각적으로 확인할 수 있습니다.

이 코드는 PyTorch를 사용하여 Grad-CAM (Gradient-weighted Class Activation Mapping)을 구현하는 것으로 보입니다. Grad-CAM은 모델의 어떤 부분이 분류 결정에 영향을 미치는지를 시각화하는 기법 중 하나입니다.

여기서 사용된 핵심 개념은 다음과 같습니다:

Hook 클래스: 이 클래스는 forward pass 동안에 특정 레이어의 활성화 값을 추출하는 역할을 합니다.

__init__: 초기화 메서드에서는 해당 레이어의 forward hook을 등록합니다. 이 hook은 hook_func 메서드를 실행합니다.
hook_func: forward hook이 호출될 때 실행되며, 활성화 값을 self.stored에 저장합니다.
__enter__ 및 __exit__: context manager로서 사용되며, 해당 레이어의 forward hook을 등록하고 제거하는 역할을 합니다.
HookBwd 클래스: 이 클래스는 backward pass 동안 특정 레이어의 gradient 값을 추출하는 역할을 합니다.

__init__: 해당 레이어의 backward hook을 등록합니다. 이 hook은 hook_func 메서드를 실행합니다.
hook_func: backward hook이 호출될 때 실행되며, gradient 값을 self.stored에 저장합니다.
__enter__ 및 __exit__: context manager로서 사용되며, 해당 레이어의 backward hook을 등록하고 제거하는 역할을 합니다.
"""

def get_gradcam(x, location=-1):
    with HookBwd(learn.model[0][location]) as hookg:
        with Hook(learn.model[0][location]) as hook:
            output = learn.model.eval()(x)
            idx = torch.argmax(output)
            act = hook.stored
        output[0, idx].backward()
        grad = hookg.stored

    w = grad[0].mean(dim=[1, 2], keepdim=True)
    heatmap = (w * act[0]).sum(0).detach().cpu()

    return heatmap

heatmap = get_gradcam(pos_x, location=-2)

print(heatmap.shape)
plt.imshow(heatmap, cmap='jet')
plt.show()

img = Image.open(pos_path)

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(img)
ax[0].axis('off')
ax[1].imshow(img)
ax[1].imshow(heatmap.cpu(), alpha=0.5, extent=(0,224,224,0),
              interpolation='bilinear', cmap='jet')
ax[1].axis('off')
plt.tight_layout()
plt.show()

heatmap = get_gradcam(neg_x, location=-1)
img = Image.open(neg_path)

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(img)
ax[0].axis('off')
ax[1].imshow(img)
ax[1].imshow(heatmap.cpu(), alpha=0.5, extent=(0,224,224,0),
              interpolation='bilinear', cmap='jet')
ax[1].axis('off')
plt.tight_layout()
plt.show()



"""
이 코드는 Grad-CAM(Gradient-weighted Class Activation Mapping) 히트맵을 해당 이미지와 함께 시각화하는 것

첫 번째 블록
python Copy code ===

img = Image.open(pos_path)

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(img)
ax[0].axis('off')
ax[1].imshow(img)
ax[1].imshow(heatmap.cpu(), alpha=0.5, extent=(0,224,224,0),
              interpolation='bilinear', cmap='jet')
ax[1].axis('off')
plt.tight_layout()
plt.show()

# ====
img = Image.open(pos_path): pos_path에 지정된 이미지 파일을 엽니다.
fig, ax = plt.subplots(1, 2, figsize=(12, 6)): 하나의 행과 두 개의 열로 구성된 두 개의 서브플롯을 가진 그림을 생성합니다.
ax[0].imshow(img): 첫 번째 서브플롯에 원본 이미지를 표시합니다.
ax[0].axis('off'): 첫 번째 서브플롯의 축 레이블과 눈금을 비활성화합니다.
ax[1].imshow(img): 두 번째 서브플롯에 다시 원본 이미지를 표시합니다.
ax[1].imshow(heatmap.cpu(), alpha=0.5, extent=(0,224,224,0), interpolation='bilinear', cmap='jet'): 두 번째 서브플롯의 이미지 위에 Grad-CAM 히트맵(컴퓨터의 CPU로 변환된)을 오버레이합니다. alpha=0.5는 히트맵의 투명도를 설정하고, extent는 히트맵의 크기를 이미지 크기와 일치하도록 지정합니다. interpolation 매개변수는 히트맵의 표시 방식을 정의하며, cmap은 히트맵의 컬러맵을 설정합니다.
ax[1].axis('off'): 두 번째 서브플롯의 축 레이블과 눈금을 비활성화합니다.
plt.tight_layout(): 서브플롯의 매개변수를 조정하여 꽉 찬 레이아웃을 만듭니다.
plt.show(): 이미지와 히트맵이 오버레이된 그림을 표시합니다.
두 번째 블록 (첫 번째 블록과 유사)
이 블록은 아마도 다른 이미지(neg_x)와 해당 Grad-CAM 히트맵을 사용하여 같은 시각화 과정을 수행할 것으로 보입니다.

두 블록은 이미지와 해당하는 Grad-CAM 히트맵을 나란히 비교하여 모델이 예측에 중요한 부분으로 간주한 이미지 영역을 시각적으로 보여줍니다."""