version: '3.8'

services:
  dogai_app:
    build: .
    container_name: dogai_app
    ports:
      - "3000:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    restart: always
    networks:
      - dogai_network

  postgres:
    image: postgres:13
    container_name: dogai_db
    environment:
      - POSTGRES_USER=rainstar
      - POSTGRES_PASSWORD=007008
      - POSTGRES_DB=dog_health
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dogai_network

volumes:
  postgres_data:

networks:
  dogai_network:
    driver: bridge 